AWSTemplateFormatVersion: '2010-09-09'
Description: RDS Database Instance

Parameters:
  DBInstanceClass:
    Type: String
    Default: db.t2.micro
    Description: RDS instance type
  DBName:
    Type: String
    Default: mydatabase
    Description: The name of the database
  MasterUsername:
    Type: String
    Default: admin
    Description: The master username for the RDS instance
  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: The master password for the RDS instance

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: !Ref DBInstanceClass
      Engine: mysql
      DBName: !Ref DBName
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      AllocatedStorage: '20'
      BackupRetentionPeriod: 7
      MultiAZ: false
      PubliclyAccessible: true

Outputs:
  DBInstanceEndpoint:
    Description: The database endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
